package com.gsbatra.expensedeck.db;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName = "goals")
public class Goal {

    // Note that if id == 0, and this is inserted, an id will be autogenerated
    public Goal(int id, String title, double amountTotal, String type, String tag, String note,
                String startDate, String endDate) {
        this.id = id;
        this.title = title;
        this.amountTotal = amountTotal;
        this.tag = tag;
        this.note = note;
        this.type = type;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    // Assign 0 to id to have it be auto generated
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "rowid")
    public int id;

    @ColumnInfo(name = "title")
    public String title;

    @ColumnInfo(name = "amountTotal")
    public double amountTotal;

    @ColumnInfo(name = "tag")
    public String tag;

    @ColumnInfo(name = "note")
    public String note;

    @ColumnInfo(name = "type")
    public String type;

    @ColumnInfo(name = "startDate")
    public String startDate;

    @ColumnInfo(name = "endDate")
    public String endDate;
}
