package com.gsbatra.expensedeck.db;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName = "transactions")
public class Transaction {

    // Note that if id == 0, and this is inserted, an id will be autogenerated
    public Transaction(int id, String title, double amount, String type, String tag, String note, String when) {
        this.id = id;
        this.title = title;
        this.amount = amount;
        this.type = type;
        this.tag = tag;
        this.note = note;
        this.when = when;
    }

    // Assign 0 to id to have it be auto generated
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "rowid")
    public int id;

    @ColumnInfo(name = "title")
    public String title;

    @ColumnInfo(name = "amount")
    public double amount;

    @ColumnInfo(name = "type")
    public String type;

    @ColumnInfo(name = "tag")
    public String tag;

    @ColumnInfo(name = "note")
    public String note;

    @ColumnInfo(name = "when")
    public String when;

    public Integer getMonth() {
        return Integer.parseInt(when.substring(0,2));
    }

    public Integer getDay() {
        return Integer.parseInt(when.substring(3,5));
    }
}
